leftnav:
- identifier: ada0dd1b-c169-4add-b26c-d05199a0e591
  name: Syllabus
  pageRef: /pages/syllabus
  weight: 10
- identifier: 01bd477a-a4d2-484f-9bd8-799241b167f8
  name: Lecture Notes and Slides
  pageRef: /pages/lecture-notes-and-slides
  weight: 20
- identifier: 7fc50c5e-08a4-407f-91e3-65236ed96d42
  name: Readings
  pageRef: /pages/readings
  weight: 30
- identifier: 61b0b05e-665a-4cd0-a6fb-96bf057f7677
  name: Problem Sets
  pageRef: /lists/problem-sets
  weight: 40
- identifier: 5b3f2013-bc2d-4436-808a-b15a0e04e516
  name: Project
  pageRef: /pages/project
  weight: 50
